name: Traefik

services:
  traefik:
    image: traefik:v${TRAEFIK_VERSION}
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic/:/etc/traefik/dynamic:ro
      - traefik-ssl-certs:/ssl-certs:rw
    environment:
      - CF_API_EMAIL
      - CF_DNS_API_TOKEN
      - CF_ZONE_API_TOKEN
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    networks:
      - traefik
      - traefik-backend
    restart: unless-stopped
    labels:
      - wud.tag.include=^v\d+\.\d+\.\d+$$
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`${DASHBOARD_FQDN}`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.middlewares.dashboard-auth.basicauth.users=${DASHBOARD_USERS}
      - traefik.http.middlewares.ipallowlist.ipAllowList.sourceRange=${IPALLOWLIST}
      - traefik.http.routers.dashboard.middlewares=dashboard-auth@docker, ipallowlist@docker

networks:
  traefik:
    name: traefik
    driver: bridge
  traefik-backend:
    driver: bridge
    name: backend

volumes:
  traefik-ssl-certs:
