global:
  checkNewVersion: false
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"
    reusePort: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "*.dhjensen.tech"
    asDefault: true

providers:
  docker:
    network: backend
    defaultRule: "Host(`{{ .ContainerName }}.dhjensen.tech`)"
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"

accessLog: {}

api:
  dashboard: true
  insecure: false

certificatesResolvers:
  cloudflare:
    acme:
      email: dhjen@outlook.com
      storage: /ssl-certs/acme.json
      dnsChallenge:
        provider: cloudflare

log:
  level: info
