entryPoints:
  web:
    address: ":80"
    reusePort: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  webinternal:
    address: ":80"
    reusePort: true
    http:
      redirections:
        entryPoint:
          to: websecureinternal
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    reusePort: true
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "*.dhjensen.tech"

  websecureinternal:
    address: ":443"
    reusePort: true
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "*.dhjensen.tech"
      middlewares:
        - ipallowlocal@docker
    asDefault: true

providers:
  docker: {}

api:
  dashboard: true
  insecure: false

tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: cloudflare
        domain:
          - main: "*.dhjensen.tech"
          - sans: []

certificatesResolvers:
  cloudflare:
    acme:
      email: dhjen@outlook.com
      storage: /ssl-certs/acme.json
      dnsChallenge:
        provider: cloudflare

log:
  level: info
